package com.codeforgeai.backend.service;

import com.codeforgeai.backend.model.ProjectRequest;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.file.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
public class ProjectBuilderService {

    public String buildProject(ProjectRequest request) throws Exception {

        // Get prompt from request
        String prompt = request.getPrompt();

        // Clean project name (safe for Windows)
        String projectName = prompt
                .toLowerCase()
                .replaceAll("[^a-z0-9]", "_")
                .replaceAll("_+", "_");

        // Base folder
        String basePath = "generated-projects/" + projectName;

        // Ensure main folder exists
        File projectDir = new File(basePath);
        if (!projectDir.exists()) {
            projectDir.mkdirs();
        }

        // Create folders
        new File(basePath + "/frontend/src").mkdirs();
        new File(basePath + "/backend/src").mkdirs();
        new File(basePath + "/database").mkdirs();

        // Create files

        createFile(basePath + "/frontend/src/App.js",
                "function App() {\n" +
                "  return (\n" +
                "    <div>\n" +
                "      <h1>Welcome to " + projectName + "</h1>\n" +
                "    </div>\n" +
                "  );\n" +
                "}\n" +
                "export default App;"
        );

        createFile(basePath + "/frontend/src/Dashboard.jsx",
                "export default function Dashboard(){\n" +
                "  return <h2>Dashboard Page</h2>;\n" +
                "}"
        );

        createFile(basePath + "/frontend/src/Login.jsx",
                "export default function Login(){\n" +
                "  return <h2>Login Page</h2>;\n" +
                "}"
        );

        createFile(basePath + "/backend/src/ProjectController.java",
                "public class ProjectController {\n" +
                "    // API endpoints here\n" +
                "}"
        );

        createFile(basePath + "/backend/src/ProjectService.java",
                "public class ProjectService {\n" +
                "    // business logic here\n" +
                "}"
        );

        createFile(basePath + "/database/schema.sql",
                "CREATE TABLE users (\n" +
                "  id INT PRIMARY KEY,\n" +
                "  name VARCHAR(100)\n" +
                ");"
        );

        createFile(basePath + "/README.md",
                "# " + projectName + "\n" +
                "Generated by CodeForgeAI"
        );

        // Create ZIP file
        String zipPath = "generated-projects/" + projectName + ".zip";
        zipFolder(projectDir, zipPath);

        System.out.println("Project generated successfully: " + projectName);

        return projectName;
    }

    // File creation helper
    private void createFile(String path, String content) throws IOException {

        File file = new File(path);

        if (!file.getParentFile().exists()) {
            file.getParentFile().mkdirs();
        }

        try (FileWriter writer = new FileWriter(file)) {
            writer.write(content);
        }
    }

    // ZIP generator
    private void zipFolder(File sourceFolder, String zipFilePath) throws IOException {

        try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(zipFilePath))) {

            Path sourcePath = sourceFolder.toPath();

            Files.walk(sourcePath).forEach(path -> {

                try {

                    if (Files.isDirectory(path)) return;

                    ZipEntry zipEntry = new ZipEntry(sourcePath.relativize(path).toString());

                    zos.putNextEntry(zipEntry);

                    Files.copy(path, zos);

                    zos.closeEntry();

                } catch (IOException e) {
                    e.printStackTrace();
                }

            });
        }
    }
}