const fs = require("fs");
const path = require("path");

exports.generateProjectFiles = (domain, technology) => {

  const projectName = `${domain}-${technology}-project`;

  const basePath = path.join(__dirname, "..", "generated", projectName);

  // Create base folder
  fs.mkdirSync(basePath, { recursive: true });

  // Server folders
  const serverPath = path.join(basePath, "server");
  fs.mkdirSync(serverPath);

  fs.mkdirSync(path.join(serverPath, "models"));
  fs.mkdirSync(path.join(serverPath, "routes"));
  fs.mkdirSync(path.join(serverPath, "controllers"));

  // Client folders
  const clientPath = path.join(basePath, "client");
  fs.mkdirSync(clientPath);

  fs.mkdirSync(path.join(clientPath, "src"));
  fs.mkdirSync(path.join(clientPath, "src", "pages"));

  // Create files

  fs.writeFileSync(
    path.join(serverPath, "server.js"),
`const express = require("express");
const app = express();

app.get("/", (req,res)=>{
 res.send("Server Running");
});

app.listen(5000,()=>{
 console.log("Server running");
});
`
  );

  fs.writeFileSync(
    path.join(serverPath, "models", "User.js"),
`const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
 name:String,
 email:String,
 password:String
});

module.exports = mongoose.model("User", userSchema);
`
  );

  fs.writeFileSync(
    path.join(clientPath, "src", "pages", "Home.jsx"),
`export default function Home(){
 return (
  <div>
   <h1>${domain} Project</h1>
   <p>Built with ${technology}</p>
  </div>
 )
}
`
  );

  fs.writeFileSync(
    path.join(basePath, "README.md"),
`# ${domain} Project

Technology: ${technology}

Generated by CodeForge AI.
`
  );

  return projectName;
};